### PR TITLE
Upgrade to Material UI 4.x

### PR DESCRIPTION
**Pull request by shssoichiro**
This repository has been on Material 0.19.x, which is a 5+ year old version with a lot of rough edges. Upgrading provides us with an easier way to implement new features. It turns out that the easiest way was to just rip off the bandaid and go straight to the latest version. The UI is not 100% identical to before, in that I tried to use more of the built-in styles inherent to Material UI. It is identical enough in that no functionality is lost and nothing should look objectively worse.

This also involved upgrading React to 16.8 and Typescript to 3.2, as both of these have new features that are required by Material 4.x. Neither of these upgrades involved any breaking changes.

Analysis views:
Screenshot_2021-05-28_18-54-10
Screenshot_2021-05-28_18-54-33
Screenshot_2021-05-28_18-54-47
Screenshot_2021-05-28_18-54-58
Screenshot_2021-05-28_18-55-09

AWCY view:
Screenshot_2021-05-28_18-55-42

### CODE REVIEW

**Comment by shssoichiro** [comment]
@tdaede @vibhoothiiaanand apparently I can't assign reviewers, so I'm manually tagging you as the go-tos.

**Comment by tdaede** [comment]
Could you rebase?

**Comment by nasirhemed** [comment]
@shssoichiro could you fix the merge conflicts ? 

- For package.json, I upgraded to 4.2.4 instead of 3.2.4. We're sorta using some stuff that appeared in ts 3.9+ plus it's the latest version
- For PlayerSplit.tsx, it's best to remove the `else if ((document as any).mozCancelFullScreen)` clause since it's `mozCancelFullScreen` is deprecated
- I think you can accept your changes on your end for Analyzer.tsx

**Comment by shssoichiro** [comment]
Rebased. I also had to lock the version of @types/react-transition-group because 4.4.1 migrates to React 17, which breaks the build. Shame on them for making a backwards incompatible change in a patch release.

**Comment by tdaede** [comment]
Did some basic tests to verify functionality, looks good.

**Review by tdaede — APPROVED** [review]

**Review by tdaede — CHANGES_REQUESTED** [review]
Actually I take that back. There still seems to be an issue on my fresh checkout building this. There are a lot of errors but they start with:

```ERROR in /home/thomas/sandbox/aomanalyzer/node_modules/@material-ui/core/node_modules/@types/react/index.d.ts
(3051,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

ERROR in /home/thomas/sandbox/aomanalyzer/node_modules/@material-ui/core/node_modules/@types/react/index.d.ts
(3062,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.


```

**Comment by tdaede** [comment]
It seems like the problem is that Material-UI ends up using React 17, rather than only React 16 as intended by this change. Either we should jump to React 17 or limit the Material-UI version to one that only picks up React 16.

**Comment by shssoichiro** [comment]
That is odd since I explicitly pinned the dependency that pulled in React 17 to an older version to prevent this. I wonder if in the past 4 days some other package has done this same thing. I'll investigate. This is the problem with not committing the package-lock.json file...

**Comment by tdaede** [comment]
I'm alright with committing the package-lock.json for this project, but we'll need to at least fix it up enough so that we can generate it once.

**Comment by shssoichiro** [comment]
I committed my working package-lock.json. Another thing to note is that I tested it with node 14 (and also added a .nvmrc file specifying that as the recommended version). I can't guarantee this will work as-is with node 16 as I believe 16 had some breaking changes in it that broke some packages.

**Comment by tdaede** [comment]
OK, I've tested it locally now and it works here. We'll still need to fix the deps at some point.

**Review by tdaede — APPROVED** [review]

**Pull request merged**
